apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: datagrid-operator-template
  annotations:
    description: >-
      oc process -f subscription.yaml -p DATAGRID_VERSION=8.2.x | oc apply -f -
objects:
- apiVersion: operators.coreos.com/v1alpha1
  kind: Subscription
  metadata:
   name: datagrid-operator
    namespace: openshift-operators
  spec:
     channel: ${DATAGRID_VERSION}
   installPlanApproval: Automatic
  name: datagrid
  source: redhat-operators
  sourceNamespace: openshift-marketplace
parameters:
- name: DATAGRID_VERSION
  description: Data Grid Version

